<?php

global $_CLASS;

$_CLASS['core_template']->assign('T_IMAGE_PATH',  'modules/forums/images/');

$this->img = array(
	'bbcode_bitfield' => '6913',

    'btn_post' => 'modules/forums/images/en/button_topic_new.gif*27*97',
    'btn_post_pm' => 'modules/forums/images/en/button_pm_new.gif*27*97',
    'btn_reply' => 'modules/forums/images/en/button_topic_reply.gif*27*97',
    'btn_reply_pm' => 'modules/forums/images/en/button_pm_reply.gif*20*90',
    'btn_locked' => 'modules/forums/images/en/button_topic_locked.gif*27*97',
    'btn_profile' => 'modules/forums/images/en/icon_user_profile.gif*20*72',
    'btn_pm' => 'modules/forums/images/en/icon_contact_pm.gif*20*72',
    'btn_delete' => 'modules/forums/images/en/icon_post_delete.gif*20*20',
    'btn_info' => 'modules/forums/images/en/icon_post_info.gif*20*20',
    'btn_quote' => 'modules/forums/images/en/icon_post_quote.gif*20*90',
    'btn_search' => 'modules/forums/images/en/icon_user_search.gif*20*72',
    'btn_edit' => 'modules/forums/images/en/icon_post_edit.gif*20*90',
    'btn_report' => 'modules/forums/images/en/icon_post_report.gif*20*20',
    'btn_email' => 'modules/forums/images/en/icon_contact_email.gif*20*72',
    'btn_www' => 'modules/forums/images/en/icon_contact_www.gif*20*72',
    'btn_icq' => 'modules/forums/images/en/icon_contact_icq.gif*20*72',
    'btn_aim' => 'modules/forums/images/en/icon_contact_aim.gif*20*72',
    'btn_yim' => 'modules/forums/images/en/icon_contact_yahoo.gif*20*72',
    'btn_msnm' => 'modules/forums/images/en/icon_contact_msnm.gif*20*72',
    'btn_jabber' => 'modules/forums/images/en/icon_contact_jabber.gif*20*72',
    'btn_online' => 'modules/forums/images/en/icon_user_online.gif*20*72',
    'btn_offline' => 'modules/forums/images/en/icon_user_offline.gif*20*72',
    'btn_friend' => '',
    'btn_foe' => '',
  
    'icon_unapproved' => 'modules/forums/images/icon_topic_unapproved.gif*18*19',
    'icon_reported' => 'modules/forums/images/icon_topic_reported.gif*18*19',
    'icon_attach' => 'modules/forums/images/icon_topic_attach.gif*18*14',
    'icon_post' => 'modules/forums/images/icon_post_target.gif*9*12',
    'icon_post_new' => 'modules/forums/images/icon_post_target_unread.gif*9*12',
    'icon_post_latest' => 'modules/forums/images/icon_topic_latest.gif*9*18',
    'icon_post_newest' => 'modules/forums/images/icon_topic_newest.gif*9*18',

    'forum' => 'modules/forums/images/forum_read.gif*25*46',
    'forum_new' => 'modules/forums/images/forum_unread.gif*25*46',
    'forum_locked' => 'modules/forums/images/forum_read_locked.gif*25*46',
    'forum_link' => 'modules/forums/images/forum_link.gif*25*46',
    'sub_forum' => 'modules/forums/images/forum_read_subforum.gif*25*46',
    'sub_forum_new' => 'modules/forums/images/forum_unread_subforum.gif*25*46',

    'folder' => 'modules/forums/images/topic_read.gif*18*19',
    'folder_moved' => 'modules/forums/images/topic_moved.gif*18*19',
    'folder_posted' => 'modules/forums/images/topic_read_mine.gif*18*19',
    'folder_new' => 'modules/forums/images/topic_unread.gif*18*19',
    'folder_new_posted' => 'modules/forums/images/topic_unread_mine.gif*18*19',

    'folder_hot' => 'modules/forums/images/topic_unread_hot.gif*18*19',
    'folder_hot_posted' => 'modules/forums/images/topic_unread_hot_mine.gif*18*19',
    'folder_hot_new' => 'modules/forums/images/topic_read_hot.gif*18*19',
    'folder_hot_new_posted' => 'modules/forums/images/topic_read_hot_mine.gif*18*19',

    'folder_locked' => 'modules/forums/images/topic_read_locked.gif*18*19',
    'folder_locked_posted' => 'modules/forums/images/topic_read_locked_mine.gif*18*19',
    'folder_locked_new' => 'modules/forums/images/topic_unread_locked.gif*18*19',
    'folder_locked_new_posted' => 'modules/forums/images/topic_unread_locked_mine.gif*18*19',

    'folder_sticky' => 'modules/forums/images/sticky_read.gif*18*19',
    'folder_sticky_posted' => 'modules/forums/images/sticky_read_mine.gif*18*19',
    'folder_sticky_new' => 'modules/forums/images/sticky_unread.gif*18*19',
    'folder_sticky_new_posted' => 'modules/forums/images/sticky_unread_mine.gif*18*19',

    'folder_announce' => 'modules/forums/images/announce_read.gif*18*19',
    'folder_announce_posted' => 'modules/forums/images/announce_read_mine.gif*18*19',
    'folder_announce_new' => 'modules/forums/images/announce_unread.gif*18*19',
    'folder_announce_new_posted' => 'modules/forums/images/announce_unread_mine.gif*18*19',
    'folder_global' => 'modules/forums/images/announce_read.gif*18*19',
    'folder_global_posted' => 'modules/forums/images/announce_read_mine.gif*18*19',
    'folder_global_new' => 'modules/forums/images/announce_unread.gif*18*19',
    'folder_global_new_posted' => 'modules/forums/images/announce_unread_mine.gif*18*19',

    'poll_left'		=> 'modules/forums/images/poll_left.gif*12*4',
    'poll_center'	=> 'modules/forums/images/poll_center.gif*12*4',
    'poll_right'	=> 'modules/forums/images/poll_right.gif*12*4',
    'attach_progress_bar' => 'modules/forums/images/upload_bar.gif*16*280',
    'karma_left' => '',
    'karma_center' => 'modules/forums/images/karma/karma{SUFFIX}.gif*6*69',
    'karma_right' => '',
    'pagination_sep' => ', ',
    'user_icon1' => '',
    'user_icon2' => '',
    'user_icon3' => '',
    'user_icon4' => '',
    'user_icon5' => '',
    'user_icon6' => '', 
    'user_icon7' => '',
    'user_icon8' => '',
    'user_icon9' => '',
    'user_icon10' => '',

	'upload_bar' => 'modules/forums/images/upload_bar.gif*16*280',
	'poll_left' => 'modules/forums/images/poll_left.gif*12*4',
	'poll_center' => 'modules/forums/images/poll_center.gif*12*',
	'poll_right' => 'modules/forums/images/poll_right.gif*12*4',
	'icon_friend' => 'modules/forums/images/',
	'icon_foe' => 'modules/forums/images/',
	
	'forum_link' => 'modules/forums/images/forum_link.gif*25*46',
	'forum_read' => 'modules/forums/images/forum_read.gif*25*46',
	'forum_read_locked' => 'modules/forums/images/forum_read_locked.gif*25*46',
	'forum_read_subforum' => 'modules/forums/images/forum_read_subforum.gif*25*46',
	'forum_unread' => 'modules/forums/images/forum_unread.gif*25*46',
	'forum_unread_locked' => 'modules/forums/images/forum_unread_locked.gif*25*46',
	'forum_unread_subforum' => 'modules/forums/images/forum_unread_subforum.gif*25*46',
	
	'topic_moved' => 'modules/forums/images/topic_moved.gif*18*19',
	
	'topic_read' => 'modules/forums/images/topic_read.gif*18*19',
	'topic_read_mine' => 'modules/forums/images/topic_read_mine.gif*18*19',
	'topic_read_hot' => 'modules/forums/images/topic_read_hot.gif*18*19',
	'topic_read_hot_mine' => 'modules/forums/images/topic_read_hot_mine.gif*18*19',
	'topic_read_locked' => 'modules/forums/images/topic_read_locked.gif*18*19',
	'topic_read_locked_mine' => 'modules/forums/images/topic_read_locked_mine.gif*18*19',
	
	'topic_unread' => 'modules/forums/images/topic_unread.gif*18*19',
	'topic_unread_mine' => 'modules/forums/images/topic_unread_mine.gif*18*19',
	'topic_unread_hot' => 'modules/forums/images/topic_unread_hot.gif*18*19',
	'topic_unread_hot_mine' => 'modules/forums/images/topic_unread_hot_mine.gif*18*19',
	'topic_unread_locked' => 'modules/forums/images/topic_unread_locked.gif*18*19',
	'topic_unread_locked_mine' => 'modules/forums/images/topic_unread_locked_mine.gif*18*19',
	
	'sticky_read' => 'modules/forums/images/sticky_read.gif*18*19',
	'sticky_read_mine' => 'modules/forums/images/sticky_read_mine.gif*18*19',
	'sticky_read_locked' => 'modules/forums/images/sticky_read_locked.gif*18*19',
	'sticky_read_locked_mine' => 'modules/forums/images/sticky_read_locked_mine.gif*18*19',
	'sticky_unread' => 'modules/forums/images/sticky_unread.gif*18*19',
	'sticky_unread_mine' => 'modules/forums/images/sticky_unread_mine.gif*18*19',
	'sticky_unread_locked' => 'modules/forums/images/sticky_unread_locked.gif*18*19',
	'sticky_unread_locked_mine' => 'modules/forums/images/sticky_unread_locked_mine.gif*18*19',
	
	'announce_read' => 'modules/forums/images/announce_read.gif*18*19',
	'announce_read_mine' => 'modules/forums/images/announce_read_mine.gif*18*19',
	'announce_read_locked' => 'modules/forums/images/announce_read_locked.gif*18*19',
	'announce_read_locked_mine' => 'modules/forums/images/announce_read_locked_mine.gif*18*19',
	'announce_unread' => 'modules/forums/images/announce_unread.gif*18*19',
	'announce_unread_mine' => 'modules/forums/images/announce_unread_mine.gif*18*19',
	'announce_unread_locked' => 'modules/forums/images/announce_unread_locked.gif*18*19',
	'announce_unread_locked_mine' => 'modules/forums/images/announce_unread_locked_mine.gif*18*19',
	
	'global_read' => 'modules/forums/images/announce_read.gif*18*19',
	'global_read_mine' => 'modules/forums/images/announce_read_mine.gif*18*19',
	'global_read_locked' => 'modules/forums/images/announce_read_locked.gif*18*19',
	'global_read_locked_mine' => 'modules/forums/images/announce_read_locked_mine.gif*18*19',
	'global_unread' => 'modules/forums/images/announce_unread.gif*18*19',
	'global_unread_mine' => 'modules/forums/images/announce_unread_mine.gif*18*19',
	'global_unread_locked' => 'modules/forums/images/announce_unread_locked.gif*18*19',
	'global_unread_locked_mine' => 'modules/forums/images/announce_unread_locked_mine.gif*18*19',
	
	'pm_read' => 'modules/forums/images/topic_read.gif*18*19',
	'pm_unread' => 'modules/forums/images/topic_unread.gif*18*19',
	
	'icon_contact_aim' => 'modules/forums/images/{LANG}/icon_contact_aim.gif*20*72',
	'icon_contact_email' => 'modules/forums/images/{LANG}/icon_contact_email.gif*20*72',
	'icon_contact_icq' => 'modules/forums/images/{LANG}/icon_contact_icq.gif*20*72',
	'icon_contact_jabber' => 'modules/forums/images/{LANG}/icon_contact_jabber.gif*20*72',
	'icon_contact_msnm' => 'modules/forums/images/{LANG}/icon_contact_msnm.gif*20*72',
	'icon_contact_pm' => 'modules/forums/images/{LANG}/icon_contact_pm.gif*20*72',
	'icon_contact_yahoo' => 'modules/forums/images/{LANG}/icon_contact_yahoo.gif*20*72',
	'icon_contact_www' => 'modules/forums/images/{LANG}/icon_contact_www.gif*20*72',
	
	'icon_post_delete' => 'modules/forums/images/{LANG}/icon_post_delete.gif*20*20',
	'icon_post_edit' => 'modules/forums/images/{LANG}/icon_post_edit.gif*20*90',
	'icon_post_info' => 'modules/forums/images/{LANG}/icon_post_info.gif*20*20',
	'icon_post_quote' => 'modules/forums/images/{LANG}/icon_post_quote.gif*20*90',
	'icon_post_report' => 'modules/forums/images/{LANG}/icon_post_report.gif*20*20',
	'icon_post_target' => 'modules/forums/images/icon_post_target.gif*9*12',
	'icon_post_target_unread' => 'modules/forums/images/icon_post_target_unread.gif*9*12',
	
	'icon_topic_attach' => 'modules/forums/images/icon_topic_attach.gif*18*14',
	'icon_topic_latest' => 'modules/forums/images/icon_topic_latest.gif*9*18',
	'icon_topic_newest' => 'modules/forums/images/icon_topic_newest.gif*9*18',
	'icon_topic_reported' => 'modules/forums/images/icon_topic_reported.gif*18*19',
	'icon_topic_unapproved' => 'modules/forums/images/icon_topic_unapproved.gif*18*19',
	
	'icon_user_online' => 'modules/forums/images/{LANG}/icon_user_online.gif*20*72',
	'icon_user_offline' => 'modules/forums/images/{LANG}/icon_user_offline.gif*20*72',
	'icon_user_profile' => 'modules/forums/images/{LANG}/icon_user_profile.gif*20*72',
	'icon_user_search' => 'modules/forums/images/{LANG}/icon_user_search.gif*20*72',
	'icon_user_warn' => 'modules/forums/images/{LANG}/icon_user_warn.gif*20*20',
	
	'button_pm_forward' => 'modules/forums/images/',
	'button_pm_new' => 'modules/forums/images/{LANG}/button_pm_new.gif*27*97',
	'button_pm_reply' => 'modules/forums/images/{LANG}/button_pm_reply.gif*20*90',
	'button_topic_locked' => 'modules/forums/images/{LANG}/button_topic_locked.gif*27*97',
	'button_topic_new' => 'modules/forums/images/{LANG}/button_topic_new.gif*27*97',
	'button_topic_reply' => 'modules/forums/images/{LANG}/button_topic_reply.gif*27*97',

);

?>