<?php

global $_CLASS;

$_CLASS['core_template']->assign('T_IMAGE_PATH',  'modules/forums/images/');

$this->img = array(
	'bbcode_bitfield' => '6913',
    'btn_post' => 'modules/forums/images/en/btn_post.gif*27*97',
    'btn_post_pm' => 'modules/forums/images/en/btn_post_pm.gif*27*97',
    'btn_reply' => 'modules/forums/images/en/btn_reply.gif*27*97',
    'btn_reply_pm' => 'modules/forums/images/en/btn_reply_pm.gif*20*90',
    'btn_locked' => 'modules/forums/images/en/btn_locked.gif*27*97',
    'btn_profile' => 'modules/forums/images/en/btn_profile.gif*20*72',
    'btn_pm' => 'modules/forums/images/en/btn_pm.gif*20*72',
    'btn_delete' => 'modules/forums/images/en/btn_delete.gif*20*20',
    'btn_info' => 'modules/forums/images/en/btn_info.gif*20*20',
    'btn_quote' => 'modules/forums/images/en/btn_quote.gif*20*90',
    'btn_search' => 'modules/forums/images/en/btn_search.gif*20*72',
    'btn_edit' => 'modules/forums/images/en/btn_edit.gif*20*90',
    'btn_report' => 'modules/forums/images/en/btn_report.gif*20*20',
    'btn_email' => 'modules/forums/images/en/btn_email.gif*20*72',
    'btn_www' => 'modules/forums/images/en/btn_www.gif*20*72',
    'btn_icq' => 'modules/forums/images/en/btn_icq.gif*20*72',
    'btn_aim' => 'modules/forums/images/en/btn_aim.gif*20*72',
    'btn_yim' => 'modules/forums/images/en/btn_yim.gif*20*72',
    'btn_msnm' => 'modules/forums/images/en/btn_msnm.gif*20*72',
    'btn_jabber' => 'modules/forums/images/en/btn_jabber.gif*20*72',
    'btn_online' => 'modules/forums/images/en/btn_online.gif*20*72',
    'btn_offline' => 'modules/forums/images/en/btn_offline.gif*20*72',
    'btn_friend' => '',
    'btn_foe' => '',
    'icon_unapproved' => 'modules/forums/images/icon_unapproved.gif*18*19',
    'icon_reported' => 'modules/forums/images/icon_reported.gif*18*19',
    'icon_attach' => 'modules/forums/images/icon_attach.gif*18*14',
    'icon_post' => 'modules/forums/images/icon_minipost.gif*9*12',
    'icon_post_new' => 'modules/forums/images/icon_minipost_new.gif*9*12',
    'icon_post_latest' => 'modules/forums/images/icon_latest_reply.gif*9*18',
    'icon_post_newest' => 'modules/forums/images/icon_newest_reply.gif*9*18',
    'forum' => 'modules/forums/images/folder_big.gif*25*46',
    'forum_new' => 'modules/forums/images/folder_new_big.gif*25*46',
    'forum_locked' => 'modules/forums/images/folder_locked_big.gif*25*46',
    'forum_link' => 'modules/forums/images/folder_link_big.gif*25*46',
    'sub_forum' => 'modules/forums/images/subfolder_big.gif*25*46',
    'sub_forum_new' => 'modules/forums/images/subfolder_new_big.gif*25*46',
    'folder' => 'modules/forums/images/folder.gif*18*19',
    'folder_moved' => 'modules/forums/images/folder_moved.gif*18*19',
    'folder_posted' => 'modules/forums/images/folder_posted.gif*18*19',
    'folder_new' => 'modules/forums/images/folder_new.gif*18*19',
    'folder_new_posted' => 'modules/forums/images/folder_new_posted.gif*18*19',
    'folder_hot' => 'modules/forums/images/folder_hot.gif*18*19',
    'folder_hot_posted' => 'modules/forums/images/folder_hot_posted.gif*18*19',
    'folder_hot_new' => 'modules/forums/images/folder_new_hot.gif*18*19',
    'folder_hot_new_posted' => 'modules/forums/images/folder_new_hot_posted.gif*18*19',
    'folder_locked' => 'modules/forums/images/folder_lock.gif*18*19',
    'folder_locked_posted' => 'modules/forums/images/folder_lock_posted.gif*18*19',
    'folder_locked_new' => 'modules/forums/images/folder_lock_new.gif*18*19',
    'folder_locked_new_posted' => 'modules/forums/images/folder_lock_new_posted.gif*18*19',
    'folder_sticky' => 'modules/forums/images/folder_sticky.gif*18*19',
    'folder_sticky_posted' => 'modules/forums/images/folder_sticky_posted.gif*18*19',
    'folder_sticky_new' => 'modules/forums/images/folder_sticky_new.gif*18*19',
    'folder_sticky_new_posted' => 'modules/forums/images/folder_sticky_new_posted.gif*18*19',
    'folder_announce' => 'modules/forums/images/folder_announce.gif*18*19',
    'folder_announce_posted' => 'modules/forums/images/folder_announce_posted.gif*18*19',
    'folder_announce_new' => 'modules/forums/images/folder_announce_new.gif*18*19',
    'folder_announce_new_posted' => 'modules/forums/images/folder_announce_new_posted.gif*18*19',
    'folder_global' => '',
    'folder_global_posted' => '',
    'folder_global_new' => '',
    'folder_global_new_posted' => '',
    'poll_left'		=> 'modules/forums/images/vote_lcap.gif*12*4',
    'poll_center'	=> 'modules/forums/images/voting_bar.gif*12*4',
    'poll_right'	=> 'modules/forums/images/vote_rcap.gif*12*4',
    'attach_progress_bar' => 'modules/forums/images/progress_bar.gif*16*280',
    'karma_left' => '',
    'karma_center' => 'modules/forums/images/karma/karma{SUFFIX}.gif*6*69',
    'karma_right' => '',
    'pagination_sep' => ', ',
    'image_register' => 'modules/forums/images/icon_mini_register.gif',
    'user_icon1' => '',
    'user_icon2' => '',
    'user_icon3' => '',
    'user_icon4' => '',
    'user_icon5' => '',
    'user_icon6' => '', 
    'user_icon7' => '',
    'user_icon8' => '',
    'user_icon9' => '',
    'user_icon10' => '',
);

?>